### ISSUE TITLE
Confusing log output

### ISSUE THREAD

**Issue by michael-o** [khmarbaise/multienv-maven-plugin#13]
I am using version 0.2.0 and have created the following environment for my WAR project:

    D:\workspace-4.5\services-webapp\src\main\environments
    └───iecmig
        ├───META-INF
        │       context.xml
        │
        └───WEB-INF
            └───classes
                    logback.xml
                    tedab-services-custom.properties

The log output is:

    [INFO] --- multienv-maven-plugin:0.2.0:environment (remote-deployments) @ services-webapp ---
    [INFO]
    [INFO] We have found 4 environments.
    [INFO] We have the following environments: iecmig,iecmig\META-INF,iecmig\WEB-INF,iecmig\WEB-INF\classes
    [INFO]
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 3 resources
    [INFO] Building Environment: 'iecmig'
    [INFO] Building jar: D:\services-webapp\target\services-webapp-0.4.2-SNAPSHOT-iecmig.war
    [INFO] Building Environment: 'iecmig\META-INF'
    [INFO] Building jar: D:\services-webapp\target\services-webapp-0.4.2-SNAPSHOT-iecmig\META-INF.war
    [INFO] Building Environment: 'iecmig\WEB-INF'
    [INFO] Building jar: D:\services-webapp\target\services-webapp-0.4.2-SNAPSHOT-iecmig\WEB-INF.war
    [INFO] Building Environment: 'iecmig\WEB-INF\classes'
    [INFO] Building jar: D:\services-webapp\target\services-webapp-0.4.2-SNAPSHOT-iecmig\WEB-INF\classes.war
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 17.822 s
    [INFO] Finished at: 2016-10-13T10:45:17+02:00
    [INFO] Final Memory: 46M/472M
    [INFO] ------------------------------------------------------------------------

The produced WAR file is fine but the log says:

1. four environments, but I do have only one
2. Building JAR though this is a WAR

It seems like the directory `environments` is deep-traversed instead of level 1.

**Comment by khmarbaise** [comment]
Looks like that...

**Comment by michael-o** [comment]
Looks better now, the follow can be collapsed into one line:

    [INFO] We have found 1 environments.
    [INFO] We have the following environments: iecmig

to

    [INFO] We have the following environment: iecmig

or 

    [INFO] We have the following 3 environments: iecmig, test, prod

**Comment by michael-o** [comment]
Additionally, the following is still misleading:

    [INFO] Building jar: D:\...\target\services-webapp.0.4.2-SNAPSHOT-iecmig.war

I would expect to read:

    [INFO] Building war: D:\...\target\services-webapp.0.4.2-SNAPSHOT-iecmig.war

`jar` is built in `configuration` goal and not `environment` goal, isn't it?
