### ISSUE TITLE
Override packaging type

### ISSUE THREAD

**Issue by zendu** [khmarbaise/multienv-maven-plugin#18]
It seems that configuration JARs created use project's packaging type. In my case, I use "war" packaging; but I would like configuration JARs to use "jar" packaging so that they are installed and deployed as JARs.

It would be great if you can add a parameter to override packaging type and use the parameter instead of project's packaging in code below.
 
![packaging-type](https://user-images.githubusercontent.com/4323295/30893368-a1a903a6-a2f2-11e7-9d21-66a8745d028d.png)

**Comment by khmarbaise** [comment]
You should configure to use the `configuration` goal instead of `environment`goals to produce separate `jar` artifacts...

**Comment by zendu** [comment]
I do use `configuration` goal to create JAR files. But those remain JAR only in build folder. Install and Deploy lifecycles of Maven rename those to WAR when installing to local repository and deploying to remote Maven repository like Artifactory.

**Comment by khmarbaise** [comment]
Can you make a sample project on github so I can take a look....

**Comment by khmarbaise** [comment]
Unfortunately you are right...

**Comment by khmarbaise** [comment]
The release has been made 0.3.1 the sync to central could take some hours...

**Comment by khmarbaise** [comment]
central sync is done so it's available the new version.
