### ISSUE TITLE
Libraries for enviroments

### ISSUE THREAD

**Issue by erickjx** [khmarbaise/multienv-maven-plugin#19]
Hi, 

With maven  i can select in profile if jar is runtime provided or compile with variable like this:

&lt;dependency&gt;
&nbsp;  &lt;groupId&gt;org.apache.cxf&lt;/groupId&gt;
&nbsp;  &lt;artifactId&gt;cxf-core&lt;/artifactId&gt;
&nbsp;  &lt;version&gt;${cxf.version}&lt;/version&gt;
&nbsp;  &lt;scope&gt;${cxf.jar.scope}&lt;/scope&gt;
&lt;/dependency&gt;

I need this, how i can do it now without profiles? Thanks.

**Comment by khmarbaise** [comment]
To be honest this sounds wrong...having different versions...I don't know what you are trying to solve? Maybe you can describe more in detail what you are trying to do...

**Comment by erickjx** [comment]
Hi, i want test project in my laptop (Jetty, Tomcat, GlassFish) for dev mode and other environments (test, productions) with others App Servesr (WildFly, WebSphere, etc).
WildFly & WebSphere need omit dome libraries to work, like Jaxb, CXF, and others.
To day i use profiles to change scope dependencies.

**Comment by khmarbaise** [comment]
In such case you should should setup environment agnostic modules with different dependencies which means that a single build will produce the different result files for all environments..Profiles is usually not the best option for that..Apart from that the multienv-maven-plugin is not intended to handle this...
