### ISSUE TITLE
Separate the dependency on main artifact

### ISSUE THREAD

**Issue by nbn** [khmarbaise/multienv-maven-plugin#20]
So, my usecase for this issue is simply that I want to separate the artfact and the environment configuration into two separate repositories (storing env passwords in the codebase is just a smell).

Looking at this plugin I like the repackaging approach, but I wanted to have it in a separate project. So I created a project which:
- had a dependency on a built project (spring boot project with default application.profiles)
- Had a few src/main/environments
- Would use dependency:copy-dependencies to 'download' my project
- Would use build-helper-maven-plugin to attach the downloaded artifact (Yes effectively renaming the artifactId)
- And then repackage the artifact into environments.

Running the plugin failed with a NPE [1] where I can see from the code, that you depend on the project.getArtifact() to have a file set, and ask artifact.getFile().isFile() on a null file.

So, that was the bug encountered... Now, I was also thinking why couldn't I specify any specific attached artifact or perhaps even better could specify a completely external artifact..

So this is basically a bug report/feature request.

If you want I could probably come up with a pull request, but interested in whether you would agree on this feature and/or simply do it yourself.

[1] Caused by: java.lang.NullPointerException
	at com.soebes.maven.plugins.multienv.EnvironmentMojo.execute(EnvironmentMojo.java:62)

**Comment by nbn** [comment]
Actually, looking at the source code, I think you may have implemented it, but if you just changed line 62 from
if ( artifact.getFile().isFile() )
to
if (artifact.getFile() != null && artifact.getFile().isFile())

Then it would go on and find the first attached artifact in my case, which was what I was hoping for.

**Comment by khmarbaise** [comment]
In particular related to Spring Boot I would suggest to use a configuration service instead ...something what Spring Boot already offers...furthermore packaging for a particular environments is in the area of (Micro-)Services in general a smell and should be prevented...Apart from that I would see that as a feature request (;-))) would it be possible that you create example project how it should look like from your point of view ? So I have a base for an integration test...

**Comment by nbn** [comment]
Agree on the fundamentals, but even with config (which is just an added abstraction) every server would still have to be identified. In my special case we have to deploy in some weblogic clusters, so I need to have a deployment plan to override that one (1) setting :)

I will generate and upload a sample of the idea for you, but I think it will be helped by a null safeguard on line 62.
