### ISSUE TITLE
manifest file is not adding with multienv-maven-plugin in maven

### ISSUE THREAD

**Issue by ishubhamjain** [khmarbaise/multienv-maven-plugin#25]
I am using multienv-maven-plugin which create multiple jars for me as per env example- dev, uat etc.

I am using dependencies as below:

          <plugin>
                <groupId>com.soebes.maven.plugins</groupId>
                <artifactId>multienv-maven-plugin</artifactId>
                <version>0.3.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>environment</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
Above plug-in create multiple jars as per env.

Now I want to add manifest file in all env jar.

I am using below plug-in

       <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <finalName>Dependencies</finalName>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>Runner.TestMethods</mainClass>
                            <classpathPrefix>dependency-jars/</classpathPrefix>
                        </manifest>
                    </archive>
                    <outputDirectory>${user.dir}/demo/Dependencies/lib/</outputDirectory>
                </configuration>
            </plugin> 
But the problem is manifest file is included/updated only in main jar not in all jars.

How I can add manifest file in all env jars using multienv-maven-plugin.

**Comment by khmarbaise** [comment]
Do you have a full working example ?

**Comment by ishubhamjain** [comment]
Hi khmarbaise

The problem is I am not getting any way to add the manifest in multi-env plugin while it is working for others plug-in.

I have created a demo project where you can see my issue.

The git URL is as below:

https://github.com/ishubhamjain/project.git

I have also pushed the target folder.

You can observe that multi-env-plug-in jar will not empty manifesto.
project-0.0.1-SNAPSHOT-dev.jar
project-0.0.1-SNAPSHOT-local.jar
project-0.0.1-SNAPSHOT-uat.jar

While the jars created by another plugin added up the manifest correctly:
project-0.0.1-SNAPSHOT.zip

unzip above zip and find jar as : project-0.0.1-SNAPSHOT.jar

I have tried to add tag of manfisto but all are throwing error.
I tried as below:

<plugin>
            <groupId>com.soebes.maven.plugins</groupId>
            <artifactId>multienv-maven-plugin</artifactId>
            <version>0.3.1</version>
            <executions>
                <execution>
                    <goals>
                        <goal>environment</goal>
                    </goals>
                </execution>
            </executions>
                    <manifest>
                        <mainClass>Runner.TestMethods</mainClass>
                    </manifest>
        </plugin>

please let me the way around .. it will be reallyhelpful ...

**Comment by khmarbaise** [comment]
Can you explain why you closed the issue?

**Comment by ishubhamjain** [comment]
@khmarbaise - that was my issue .. I was not putting  <archive> and  <manifest> tags inside muti env plug-in. once I realize, it stated working for me

     <archive>
                    <manifest>
                        <addClasspath>true</addClasspath>
                        <mainClass>Runner.TestMethods</mainClass>
                        <classpathPrefix>dependency-jars/</classpathPrefix>
                    </manifest>
                </archive>

I have create a same project and now it is working for me

https://github.com/ishubhamjain/project.git

Thanks for you time :)

**Comment by khmarbaise** [comment]
Ok. Thanks for the feedback. So I know it's not a bug...
